### ISSUE TITLE
Fix the issue of videos in main app dependent on library app

### ISSUE THREAD

**Issue by pai-meghna** [XPRIZE/GLEXP-Team-KitkitSchool#21]

**Comment by jo-xprize** [comment]
@pai-meghna When installing the mainapp as a standalone app (without installing the library app), and opening a video, it does not load:

![Screenshot_2019-06-21-18-51-40-618_com enuma xprize](https://user-images.githubusercontent.com/42047517/59941823-114f0380-9456-11e9-8b29-596746c05b30.png)

![Screenshot_2019-06-21-18-51-59-861_com enuma xprize](https://user-images.githubusercontent.com/42047517/59941825-13b15d80-9456-11e9-814b-ee0a95aa38af.png)

![Screenshot_2019-06-21-18-52-06-615_com enuma xprize](https://user-images.githubusercontent.com/42047517/59941831-16ac4e00-9456-11e9-865f-912cce89248b.png)

![Screenshot_2019-06-21-18-52-33-172_com enuma xprize](https://user-images.githubusercontent.com/42047517/59941843-21ff7980-9456-11e9-994d-ee56219c9b26.png)

![Screenshot_2019-06-21-18-52-22-549_com enuma xprize](https://user-images.githubusercontent.com/42047517/59941849-24fa6a00-9456-11e9-9fe3-ca97c70879c0.png)

![Screenshot_2019-06-21-18-52-16-768_com enuma xprize](https://user-images.githubusercontent.com/42047517/59941853-27f55a80-9456-11e9-899b-b1ede4894b5c.png)

Is there a corresponding pull request for this GitHub issue?
