### ISSUE TITLE
Debugging Bookviewer

### ISSUE THREAD

**Issue by pbehghader** [XPRIZE/GLEXP-Team-KitkitSchool#31]
What tool(s) should we use to be able to debug bookviewer/Classes C++ files?

**Comment by ankitk20** [comment]
Android Studio has the capability to do it.

**Comment by ankitk20** [comment]
Android Studio can do it.

**Comment by jo-xprize** [comment]
Closing this issue.

@pbehghader Were you able to debug the files?
